apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name:  "{{ .Values.job.name }}"
  namespace: "{{ .Values.job.namespace }}"
spec:
  concurrencyPolicy: Forbid
  schedule: "{{ .Values.job.schedule }}"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName:  "{{ .Values.accountName.name }}"
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command: [ "/bin/sh", "-c" ]
              args: 
                - 'kubectl delete pod --field-selector=status.phase==Running'
