apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Values.accountName.name }}"
  namespace: "{{ .Values.job.namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ .Values.accountName.name }}"
subjects:
  - kind: ServiceAccount
    name:  "{{ .Values.accountName.name }}"