kind: ServiceAccount
apiVersion: v1
metadata:
  name: "{{ .Values.accountName.name }}"
  namespace: "{{ .Values.namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Values.accountName.name }}"
  namespace: "{{ .Values.namespace }}"
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "patch", "list", "watch", "delete"]